/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as BillingReturnRouteImport } from './routes/billing.return'
import { Route as AuthenticatedCollabsIdRouteImport } from './routes/_authenticated/collabs.$id'
import { Route as AuthenticatedCollabsNewRouteImport } from './routes/_authenticated/collabs.new'
import { Route as ApiPublicHooksLinqSignupRouteImport } from './routes/api/public/hooks/linq-signup'
import { Route as ApiPublicHooksRemindersRouteImport } from './routes/api/public/hooks/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BillingReturnRoute = BillingReturnRouteImport.update({
  id: '/billing/return',
  path: '/billing/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCollabsIdRoute = AuthenticatedCollabsIdRouteImport.update({
  id: '/collabs/$id',
  path: '/collabs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollabsNewRoute = AuthenticatedCollabsNewRouteImport.update({
  id: '/collabs/new',
  path: '/collabs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksLinqSignupRoute =
  ApiPublicHooksLinqSignupRouteImport.update({
    id: '/api/public/hooks/linq-signup',
    path: '/api/public/hooks/linq-signup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRemindersRoute = ApiPublicHooksRemindersRouteImport.update({
  id: '/api/public/hooks/reminders',
  path: '/api/public/hooks/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/upgrade': typeof UpgradeRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/home': typeof AuthenticatedHomeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/billing/return': typeof BillingReturnRoute
  '/collabs/$id': typeof AuthenticatedCollabsIdRoute
  '/collabs/new': typeof AuthenticatedCollabsNewRoute
  '/api/public/hooks/linq-signup': typeof ApiPublicHooksLinqSignupRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/upgrade': typeof UpgradeRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/home': typeof AuthenticatedHomeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/billing/return': typeof BillingReturnRoute
  '/collabs/$id': typeof AuthenticatedCollabsIdRoute
  '/collabs/new': typeof AuthenticatedCollabsNewRoute
  '/api/public/hooks/linq-signup': typeof ApiPublicHooksLinqSignupRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/upgrade': typeof UpgradeRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/billing/return': typeof BillingReturnRoute
  '/_authenticated/collabs/$id': typeof AuthenticatedCollabsIdRoute
  '/_authenticated/collabs/new': typeof AuthenticatedCollabsNewRoute
  '/api/public/hooks/linq-signup': typeof ApiPublicHooksLinqSignupRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/upgrade'
    | '/calendar'
    | '/home'
    | '/settings'
    | '/billing/return'
    | '/collabs/$id'
    | '/collabs/new'
    | '/api/public/hooks/linq-signup'
    | '/api/public/hooks/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/upgrade'
    | '/calendar'
    | '/home'
    | '/settings'
    | '/billing/return'
    | '/collabs/$id'
    | '/collabs/new'
    | '/api/public/hooks/linq-signup'
    | '/api/public/hooks/reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/upgrade'
    | '/_authenticated/calendar'
    | '/_authenticated/home'
    | '/_authenticated/settings'
    | '/billing/return'
    | '/_authenticated/collabs/$id'
    | '/_authenticated/collabs/new'
    | '/api/public/hooks/linq-signup'
    | '/api/public/hooks/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  UpgradeRoute: typeof UpgradeRoute
  BillingReturnRoute: typeof BillingReturnRoute
  ApiPublicHooksLinqSignupRoute: typeof ApiPublicHooksLinqSignupRoute
  ApiPublicHooksRemindersRoute: typeof ApiPublicHooksRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/billing/return': {
      id: '/billing/return'
      path: '/billing/return'
      fullPath: '/billing/return'
      preLoaderRoute: typeof BillingReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/collabs/$id': {
      id: '/_authenticated/collabs/$id'
      path: '/collabs/$id'
      fullPath: '/collabs/$id'
      preLoaderRoute: typeof AuthenticatedCollabsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collabs/new': {
      id: '/_authenticated/collabs/new'
      path: '/collabs/new'
      fullPath: '/collabs/new'
      preLoaderRoute: typeof AuthenticatedCollabsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/linq-signup': {
      id: '/api/public/hooks/linq-signup'
      path: '/api/public/hooks/linq-signup'
      fullPath: '/api/public/hooks/linq-signup'
      preLoaderRoute: typeof ApiPublicHooksLinqSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reminders': {
      id: '/api/public/hooks/reminders'
      path: '/api/public/hooks/reminders'
      fullPath: '/api/public/hooks/reminders'
      preLoaderRoute: typeof ApiPublicHooksRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCollabsIdRoute: typeof AuthenticatedCollabsIdRoute
  AuthenticatedCollabsNewRoute: typeof AuthenticatedCollabsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCollabsIdRoute: AuthenticatedCollabsIdRoute,
  AuthenticatedCollabsNewRoute: AuthenticatedCollabsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  UpgradeRoute: UpgradeRoute,
  BillingReturnRoute: BillingReturnRoute,
  ApiPublicHooksLinqSignupRoute: ApiPublicHooksLinqSignupRoute,
  ApiPublicHooksRemindersRoute: ApiPublicHooksRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
